### ISSUE TITLE
Feature Request: Optional Syntax Highlighting with "Link to Github" Feature

### ISSUE THREAD

**Issue by katosh** [TDKorn/sphinx-github-style#1]
Hey there,

Thanks for making sphinx_github_style! I really like the "link to Github" feature, referenceing the right commit hash and line numbers in our docs. It's exactly what we need.

But there's one small thing: the syntax highlighting that comes with it doesn't match our light-themed documentation page. It's a bit of a clash.

Would it be possible to have an option in `conf.py` to turn off or change the syntax highlighting? That way, we could use the Github linking without changing our page's look.

Your package is great, and this tweak would make it perfect for us. Thanks for considering it!

**Comment by TDKorn** [comment]
Hey! You can just set the [```pygments_style```](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-pygments_style) confval and it'll override the one that's added by this package.

I see you're using the `furo` theme which seems to use the `tango` style, so just add this to your ```conf.py```:

```python
pygments_style = "tango"
```

Let me know if you'd still prefer to have the option to disable the syntax highlighting though, it's an easy change to make.

**Comment by katosh** [comment]
Hi @TDKorn. Thank you for the quick reply! Using `pygments_style = "tango"` works perfectly!
