### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by f0uriest** [TDKorn/sphinx-github-style#2]
Running sphinx with `-j` I get the following warning:

```
WARNING: the sphinx_github_style.meth_lexer extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```

I have sphinx set up to fail on warnings so it's kind of annoying. Any ideas?

**Comment by TDKorn** [comment]
Hey @f0uriest, the lexer hasn't been an extension since `v1.1.0`. Easiest solution is to update the pinned version (I'd suggest `v1.2.0`).

If you'd prefer to stick with the older version, then you'll somehow need to add this to the `setup()` function in meth_lexer.py

```python
return {'version': sphinx.__display_version__, 'parallel_read_safe': True}
```
